export default {
  login: 'Login',
  register: 'Register',
  userName: 'Username....',
  emailPlaceholder: 'Email....',
  pwdPlaceholder: 'Password....',
  confirmPwdPlaceholder: 'Confirm Password....',
  noAccount: "You don't have any account please ",
  already: 'Already account',
  next:'Next',
  back: 'Back',
  develop_by: 'Develop By',
  security: 'Security',
  logout: 'Logout',
  price: 'Price',
  addToCart: 'Add to cart',
  successAdded: 'Successfully added',
};
