export default {
  login: 'အကောင့်ဝင်ရန်',
  register: 'အကောင့်ဖွင့်ရန်',
  userName: 'အမည်....',
  emailPlaceholder: 'အီးမေးလ်....',
  pwdPlaceholder: 'လျို၀ှက်နံပါတ်....',
  confirmPwdPlaceholder: 'လျို၀ှက်နံပါတ် ထပ်မံရိုက်ပါ...',
  noAccount: 'အကောင့်မရှိပါက ',
  already: 'အကောင့်ရှိလျှင်',
  next: 'ရှေ့သို့',
  back: 'နောက်သို့',
  develop_by: 'ဖန်တီးသူ : ',
  security: 'လုံခြုံရေး',
  logout: 'အကောင့်ထွက်ရန်',
  price: 'စျေးနှုန်း',
  addToCart: 'စျေးခြင်း',
  successAdded: 'အောင်မြင်စွာထည့်ပြီး',
};
